spring:
  application:
    name: digital-assets-management-service
  profiles:
    active: dev

# カスタム設定
config:
  #  どの実装クラスを通じて外部AIサービスを呼び出すか (http/spring)
  ai: http
  tag:
  #  どの実装クラスを通じてタグ追加イベントを送信するか (event/mq)
    add: event
