spring:
  application:
    name: dam-service
  profiles:
    active: dev

# カスタム設定
config:
  ai:
    #  どの実装クラスを通じて外部AIサービスを呼び出すか (mock/http/spring)
    method: spring
  tag:
    #  どの実装クラスを通じてタグ追加イベントを送信するか (event/mq)
    add: event
  #  どの実装クラスを通じて定時タスクを実行するか(xxl)
#  task: xxl
